__version__ = "0.1.0"

from .client import WeatherClient
from .exceptions import (
    GeocodingError,
    LocationNotInPJMError,
    NCEIAPIError,
    NCEIAuthError,
    NoStationFoundError,
    NWSAPIError,
    SatelliteAPIError,
    TemperatureModelingError,
)
from .models import (
    Coordinates,
    ForecastPeriod,
    ForecastSample,
    HourlyForecast,
    LeadTimeSkill,
    Location,
    SatelliteObservation,
    TemperatureObservation,
    WeatherResult,
)
from .verification import record_forecast, load_verification_stats
from .features import (
    ClimateNormals,
    FEATURE_FIELDS,
    FEATURE_FIELDS_ERA5,
    FEATURE_FIELDS_SAT,
    FEATURE_FIELDS_ENS,
    FeatureVector,
    build_climate_normals,
    extract_features,
)
from .correction import (
    CorrectionModel,
    CorrectionResult,
    ModelEvaluation,
    train_correction_model,
    train_and_evaluate,
    train_and_evaluate_banded,
)

__all__ = [
    "WeatherClient",
    "WeatherResult",
    "Location",
    "Coordinates",
    "TemperatureObservation",
    "ForecastPeriod",
    "HourlyForecast",
    "SatelliteObservation",
    "ForecastSample",
    "LeadTimeSkill",
    "record_forecast",
    "load_verification_stats",
    "ClimateNormals",
    "FEATURE_FIELDS",
    "FEATURE_FIELDS_ERA5",
    "FEATURE_FIELDS_SAT",
    "FEATURE_FIELDS_ENS",
    "FeatureVector",
    "build_climate_normals",
    "extract_features",
    "CorrectionModel",
    "CorrectionResult",
    "ModelEvaluation",
    "train_correction_model",
    "train_and_evaluate",
    "train_and_evaluate_banded",
    "TemperatureModelingError",
    "GeocodingError",
    "LocationNotInPJMError",
    "NWSAPIError",
    "NCEIAPIError",
    "NCEIAuthError",
    "NoStationFoundError",
    "SatelliteAPIError",
]
